# Generated by Django 4.1.2 on 2022-10-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_age_gte_18_user_age_gte_0'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='age_gte_0',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.DecimalField(decimal_places=2, default=170, max_digits=5),
            preserve_default=False,
        ),
    ]
